import { AlertCircle, Clock3, ExternalLink, Inbox, RotateCcw } from "lucide-react";
import type { EmailItem } from "../types";
import { EmptyState } from "./ui";

const formatter = new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" });
export function EmailTable({ emails, mode, onRetry }: { emails: EmailItem[]; mode: "scheduled" | "sent" | "failed"; onRetry?: (id: string) => void }) {
  if (!emails.length) return <EmptyState icon={mode === "scheduled" ? <Clock3 /> : <Inbox />} title={`No ${mode} emails`} description={mode === "scheduled" ? "Create a campaign and your upcoming emails will appear here." : "Delivered emails and their Ethereal previews will appear here."} />;
  return <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead><tr className="border-b border-slate-100 text-[11px] uppercase tracking-wider text-slate-400"><th>Recipient</th><th>Subject</th><th>{mode === "sent" ? "Sent at" : "Scheduled for"}</th><th>Status</th><th className="text-right">Action</th></tr></thead><tbody>{emails.map(email => <tr key={email.id} className="border-b border-slate-100 text-sm last:border-0 hover:bg-slate-50/60"><td><p className="font-medium text-ink">{email.recipient}</p><p className="mt-1 text-xs text-slate-400">From {email.campaign.sender.email}</p></td><td className="max-w-xs"><p className="truncate font-medium text-slate-700">{email.campaign.subject}</p>{email.lastError && <p className="mt-1 flex items-center gap-1 truncate text-xs text-red-500"><AlertCircle className="h-3 w-3" />{email.lastError}</p>}</td><td className="text-slate-500">{formatter.format(new Date(mode === "sent" ? email.sentAt! : email.scheduledAt))}</td><td><span className={`status status-${email.status.toLowerCase()}`}>{email.status.toLowerCase()}</span></td><td className="text-right">{email.previewUrl ? <a className="inline-flex items-center gap-1 text-xs font-medium text-mint-600" target="_blank" rel="noreferrer" href={email.previewUrl}>Preview <ExternalLink className="h-3 w-3" /></a> : mode === "failed" && onRetry ? <button className="inline-flex items-center gap-1 text-xs font-medium text-mint-600" onClick={() => onRetry(email.id)}><RotateCcw className="h-3 w-3" />Retry</button> : <span className="text-slate-300">—</span>}</td></tr>)}</tbody></table></div>;
}
